/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal install. It is checked in here
// so TypeScript path aliases work immediately after cloning.
